name: kname
description: A Dart package for offline Khmer name generation and utilities
version: 0.1.1
homepage: https://github.com/sovanken/kname
repository: https://github.com/sovanken/kname
issue_tracker: https://github.com/sovanken/kname/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/khmer_names.json
